services:
  djangoserver:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis


  celery:
    #container_name: celery
    build: .
    command: celery -A core worker -l INFO --concurrency=4 -Q celery
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/app  

  flower:
    build: .
    container_name: flower
    command: celery -A core flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - djangoserver