# Generated by Django 5.2.5 on 2025-08-24 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('regular', 'Regular'), ('rss', 'RSS'), ('automated', 'Automated')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_line', models.CharField(max_length=255)),
                ('preview_text', models.TextField(blank=True, default='', max_length=255)),
                ('from_name', models.CharField(max_length=120)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('to_name_format', models.CharField(blank=True, default='', max_length=120)),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('editor_json', models.JSONField(blank=True, default=dict)),
                ('inline_css', models.BooleanField(default=True)),
                ('auto_footer', models.BooleanField(default=True)),
                ('web_version_enabled', models.BooleanField(default=True)),
                ('permalink_slug', models.SlugField(blank=True, default='', help_text='Public archive slug', max_length=220)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone_str', models.CharField(default='UTC', max_length=64)),
                ('per_recipient_local_time', models.BooleanField(default=False)),
                ('resend_to_non_openers_after_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('track_google_analytics', models.BooleanField(default=False)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('utm_content', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_campaign_id', models.CharField(blank=True, default='', max_length=120)),
                ('envelope_sender', models.EmailField(blank=True, default='', max_length=254)),
                ('dkim_domain', models.CharField(blank=True, default='', max_length=255)),
                ('dkim_selector', models.CharField(blank=True, default='', max_length=63)),
                ('spf_domain', models.CharField(blank=True, default='', max_length=255)),
                ('throttle_per_minute', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('batch_size', models.PositiveIntegerField(default=1000)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('send_job_id', models.CharField(blank=True, default='', max_length=120)),
                ('started_sending_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('provider_status', models.CharField(choices=[('none', 'None'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='none', max_length=20)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('hard_bounce_count', models.PositiveIntegerField(default=0)),
                ('soft_bounce_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('unique_open_count', models.PositiveIntegerField(default=0)),
                ('open_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('click_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unsub_count', models.PositiveIntegerField(default=0)),
                ('spam_complaint_count', models.PositiveIntegerField(default=0)),
                ('ab_enabled', models.BooleanField(default=False)),
                ('ab_criterion', models.CharField(blank=True, default='', max_length=40)),
                ('ab_split_percent', models.PositiveSmallIntegerField(default=50)),
                ('ab_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ab_winner_metric', models.CharField(blank=True, default='', max_length=40)),
                ('ab_variant_a_subject', models.CharField(blank=True, default='', max_length=255)),
                ('ab_variant_b_subject', models.CharField(blank=True, default='', max_length=255)),
                ('ab_winner', models.CharField(blank=True, default='', max_length=1)),
                ('social_title', models.CharField(blank=True, default='', max_length=120)),
                ('social_description', models.CharField(blank=True, default='', max_length=200)),
                ('social_image_url', models.URLField(blank=True, default='')),
                ('include_mailing_address', models.BooleanField(default=True)),
                ('include_unsubscribe_link', models.BooleanField(default=True)),
                ('gdpr_note', models.TextField(blank=True, default='')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='audience.audience')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='campaign_ca_status_3c4318_idx'), models.Index(fields=['provider_status'], name='campaign_ca_provide_87dd48_idx'), models.Index(fields=['scheduled_at'], name='campaign_ca_schedul_9febcd_idx'), models.Index(fields=['audience', 'status'], name='campaign_ca_audienc_016e44_idx')],
            },
        ),
    ]
