# Generated by Django 5.2.5 on 2025-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_remove_campaign_campaign_ca_provide_87dd48_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='click_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_click_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_click_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unique_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
