# Generated by Django 5.2.5 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_click_count_campaign_click_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
