# Generated by Django 5.2.5 on 2025-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='compiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='compiled_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='linkset_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
