# Generated by Django 5.2.5 on 2025-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
        ('campaign', '0006_campaign_compiled_at_campaign_compiled_html_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaign_ca_audienc_016e44_idx',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['audience', 'status', 'kind'], name='campaign_ca_audienc_8e1315_idx'),
        ),
    ]
