# Generated by Django 5.2.5 on 2025-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaign_campaign_ca_audienc_016e44_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='draft', max_length=20),
        ),
    ]
