# Generated by Django 5.2.5 on 2025-08-16 15:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('cleaned', 'Cleaned'), ('Pending', 'Pending')], db_index=True, default='subscribed', max_length=20)),
                ('signup_source', models.CharField(choices=[('import', 'Import'), ('form', 'Form'), ('api', 'API'), ('manual', 'Manual')], default='import', max_length=20)),
                ('merge_fields', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('last_changed', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('timestamp_signup', models.DateTimeField(blank=True, null=True)),
                ('ip_signup', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp_opt', models.DateTimeField(blank=True, null=True)),
                ('ip_opt', models.GenericIPAddressField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='audience.audience')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='audience.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='audience.audience')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('audience', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='audience.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_contacts', to='audience.tag')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='audience.ContactTag', to='audience.tag'),
        ),
        migrations.AddIndex(
            model_name='contacttag',
            index=models.Index(fields=['tag', 'contact'], name='audience_co_tag_id_49d629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('contact', 'tag')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['audience', 'created_at'], name='audience_co_audienc_65c23e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['audience', 'status', 'created_at'], name='audience_co_audienc_2bcdd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('audience', 'email_address')},
        ),
    ]
