# Generated by Django 5.2.5 on 2025-09-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0002_alter_tag_unique_together_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tags',
            new_name='old_tags',
        ),
    ]
