# Generated by Django 5.2.5 on 2025-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0003_rename_tags_contact_old_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='audience.tag'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='old_tags',
            field=models.ManyToManyField(blank=True, related_name='old_contacts', through='audience.ContactTag', to='audience.tag'),
        ),
    ]
