# Generated by Django 5.2.5 on 2025-09-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0004_contact_tags_alter_contact_old_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='old_tags',
        ),
    ]
