# Generated by Django 5.2.5 on 2025-09-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0005_remove_contact_old_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTag',
        ),
    ]
