# Generated by Django 5.2.5 on 2025-08-27 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience', '0001_initial'),
        ('campaign', '0004_campaign_click_count_campaign_click_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaign.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='audience.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('redirect', 'Redirect'), ('webhook', 'Webhook'), ('test', 'Test')], default='redirect', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='campaign.campaign')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='tracking.campaignlink')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='audience.contact')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaignlink',
            index=models.Index(fields=['campaign'], name='tracking_ca_campaig_af7dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlink',
            index=models.Index(fields=['token'], name='tracking_ca_token_7bb5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'recipient'], name='tracking_ca_campaig_1d3f02_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['recipient'], name='tracking_ca_recipie_e915ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient'), name='uniq_campaign_recipient'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['campaign', 'occurred_at'], name='tracking_cl_campaig_ad59bf_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['link', 'occurred_at'], name='tracking_cl_link_id_ef1d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['recipient', 'occurred_at'], name='tracking_cl_recipie_b9f187_idx'),
        ),
    ]
